spring:
  application:
    name: discovery-eureka
server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    service-url:
      #将自己注册到peer2上去
      defaultZone: http://localhost:8761/eureka/
  instance:
    #指定当profiles=peer1时 主机名是peer1
    hostname: peer1
#---
#spring:
#  profiles: peer1
#
#---
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      #将自己注册到peer1上去
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: peer2
