server:
  port: 8010
spring:
  application:
    name: consumer-movie

eureka:
  client:
    service-url:
      defaultZone: http://yanjunmin:yanjunmin123@localhost:8761/eureka,http://yanjunmin:yanjunmin123@localhost:8762/eureka
  instance:
    prefer-ip-address: true
