
server:
  port: 8040
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://yanjunmin:yanjunmin123@localhost:8761/eureka,http://yanjunmin:yanjunmin123@localhost:8762/eureka