server:
  port: 8000
spring:
  application:
    name: provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  config: classpath:logback-spring.xml
#logging:
#  level: info
eureka:
  client:
    service-url:
      defaultZone: http://yanjunmin:yanjunmin123@localhost:8761/eureka,http://yanjunmin:yanjunmin123@localhost:8762/eureka
  instance:
    prefer-ip-address: true