server:
  port: 8031
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://yanjunmin:yanjunmin123@localhost:8761/eureka,http://yanjunmin:yanjunmin123@localhost:8762/eureka
  instance:
    prefer-ip-address: true
turbine:
  app-config: consumer-movie
  cluster-name-expression: "'default'"